name: warpinator
description: "Warpinator port to Flutter. A file sharing application for local networks."
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ^3.5.4

dependencies:
  cupertino_icons: ^1.0.8
  # Use dynamic_system_colors instead of dynamic_color as the latter
  # is unmaintained and yielding wrong results
  dynamic_system_colors: ^1.8.0
  end_padding: ^1.0.1
  expand: ^1.2.0
  flutter:
    sdk: flutter
  flutter_localization: ^0.3.1
  flutter_native_splash: ^2.4.4
  flutter_slidable: ^4.0.0
  flutter_svg: ^2.0.17
  go_router: ^14.8.1
  grpc: ^4.0.4
  intl: ^0.19.0
  introduction_screen: ^3.1.17
  master_detail_flow: ^3.1.0
  protobuf: ^4.0.0
  provider: ^6.1.4
  quick_actions: ^1.1.0
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/warpinator.svg
    - assets/states/
    - assets/text/
    